name: Fix JSON and Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  fix-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Download original JSON
        run: curl -s https://aio.zxcvbn.fyi/r/repo.altstore.json -o repo.altstore.json

      - name: Fix JSON (deduplicate and keep latest)
        run: |
          python << 'EOF'
          import json
          from datetime import datetime

          with open("repo.altstore.json", "r", encoding="utf-8") as f:
              data = json.load(f)

          apps_by_id = {}

          for app in data.get("apps", []):
              bid = app.get("bundleIdentifier")
              if not bid:
                  continue

              current_best = apps_by_id.get(bid)
              if current_best is None:
                  apps_by_id[bid] = app
              else:
                  d1 = app.get("versionDate") or ""
                  d2 = current_best.get("versionDate") or ""
                  try:
                      if datetime.fromisoformat(d1) > datetime.fromisoformat(d2):
                          apps_by_id[bid] = app
                  except Exception:
                      if app.get("version", "") > current_best.get("version", ""):
                          apps_by_id[bid] = app

          data["apps"] = list(apps_by_id.values())

          with open("repo.fixed.json", "w", encoding="utf-8") as f:
              json.dump(data, f, indent=2, ensure_ascii=False)
          EOF

      - name: Commit fixed JSON to repo
        run: |
          cp repo.fixed.json repo.altstore.json
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add repo.altstore.json
          git commit -m "chore: update fixed repo.altstore.json" || echo "No changes to commit"
          git push

      - name: Upload fixed JSON to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest-fixed"
          name: "Latest Fixed JSON"
          body: "Repo JSON ripulito e valido per SideStore."
          files: repo.fixed.json
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
