name: Fix JSON and Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # ogni notte alle 01:00 UTC

permissions:
  contents: write   # serve per creare release

jobs:
  fix-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Download original JSON
        run: curl -s https://aio.zxcvbn.fyi/r/repo.altstore.json -o repo.altstore.json

      - name: Fix JSON (remove duplicates)
        run: |
          python << 'EOF'
          import json

          with open("repo.altstore.json", "r", encoding="utf-8") as f:
              data = json.load(f)

          apps_by_id = {}
          new_apps = []

          for app in data.get("apps", []):
              bid = app.get("bundleIdentifier")
              if not bid:
                  continue

              if bid not in apps_by_id:
                  # Prima volta che vediamo questa app
                  apps_by_id[bid] = app
                  if "versions" not in app:
                      app["versions"] = []
                  new_apps.append(app)
              else:
                  # App duplicata → spostiamo la versione dentro quella principale
                  if "versions" in app:
                      apps_by_id[bid]["versions"].extend(app["versions"])
                  else:
                      version_entry = {
                          "version": app.get("version", ""),
                          "date": app.get("versionDate", ""),
                          "size": app.get("size", 0),
                          "downloadURL": app.get("downloadURL", ""),
                          "localizedDescription": app.get("localizedDescription", "")
                      }
                      apps_by_id[bid]["versions"].append(version_entry)

          data["apps"] = new_apps

          with open("repo.fixed.json", "w", encoding="utf-8") as f:
              json.dump(data, f, indent=2, ensure_ascii=False)
          EOF

      - name: Upload fixed JSON to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest-fixed"
          name: "Latest Fixed JSON"
          body: "Repo JSON ripulito dai duplicati (es. Kodi)."
          files: repo.fixed.json
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
